name: Deploy API Gateway

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/ptk-gateway-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/ptk-gateway-api:latest

    - name: SSH and Deploy to Kubernetes
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          kubectl set image deployment/gateway-deployment gateway=${{ secrets.DOCKER_USERNAME }}/ptk-gateway-api:latest
          kubectl rollout restart deployment/gateway-deployment
